#!/bin/sh

# Exit immediately if any command exits with a non-zero status
set -e

# Check if the script is executed with root privileges
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run with root privileges. Please use 'sudo' to execute it."
    exit 1
fi

# Check the output of uname command
kernel=$(uname -s)

if [ ! -d "gnustep-src" ] ; then
  mkdir gnustep-src
fi
cd gnustep-src
git clone https://github.com/gnustep/tools-scripts

if [ "$kernel" = "FreeBSD" ]; then
  echo "Running on FreeBSD"
  sed -i '' -e "s|/bin/bash|/bin/sh|g" tools-scripts/clone-all-repos-https
fi

./tools-scripts/clone-all-repos-https || exit 1

if [ "$kernel" = "FreeBSD" ]; then
  echo "Running on FreeBSD"
  sed -i '' -e "s|pkg install|pkg install -y|g" tools-scripts/install-dependencies-freebsd
  ./tools-scripts/install-dependencies-freebsd || exit 1
  sed -i '' -e 's|GNUSTEP_ROOT=${USR_ROOT}/GNUstep|GNUSTEP_ROOT="/"|g' tools-scripts/build-freebsd
  ./tools-scripts/build-freebsd || exit 1
  ln -s /System/Library/Makefiles/GNUstep.sh /etc/profile.d/GNUstep.sh
fi

if [ "$kernel" = "Linux" ]; then
  echo "Running on Linux"
  ./tools-scripts/install-dependencies-linux || exit 1
  ./tools-scripts/clang-setup || exit 1
  sed -i '2iset -e' tools-scripts/build-linux
  sed -i '2iset -e' tools-scripts/clang-build
  sed -i '2iset -e' tools-scripts/compile-all
  sed -i "s|/usr/GNUstep|/|g" tools-scripts/clang-build
  sed -i "s|/usr/GNUstep/System/Library/Makefiles/GNUstep.sh|/System/Library/Makefiles/GNUstep.sh|g" tools-scripts/compile-all
  ./tools-scripts/build-linux || exit 1
  sed -i '2iset -e' tools-scripts/build-libs-tools-apps
  sed -i "s|/usr/GNUstep/System/Library/Makefiles/GNUstep.sh|/System/Library/Makefiles/GNUstep.sh|g" tools-scripts/build-libs-tools-apps
fi

if [ "$kernel" = "FreeBSD" ]; then
  echo "Running on FreeBSD"
  sed -i '' -e "s|/bin/bash|/bin/sh|g" tools-scripts/build-libs-tools-apps
  sed -i '' -e "s|make -j${CPUS}|gmake -j${CPUS}|g" tools-scripts/build-libs-tools-apps
  sed -i '' -e 's|make GNUSTEP_INSTALLATION_DOMAIN=SYSTEM|gmake GNUSTEP_INSTALLATION_DOMAIN=SYSTEM|g' tools-scripts/build-libs-tools-apps
  sed -i '' -e "s|/usr/GNUstep/System/Library/Makefiles/GNUstep.sh|/System/Library/Makefiles/GNUstep.sh|g" tools-scripts/build-libs-tools-apps
fi

./tools-scripts/build-libs-tools-apps || exit 1